export enum AppRoutes {
  Home = "",
  Dashboard = "dashboard",
  Register = "register",
  ConfirmEmail = "confirm-email",
  ConfirmEmailCheckCode = "confirm-email-check-code",
  ForgotPassword = "forgot-password",
  Login = "login",
  Logout = "logout",
  ConnectWithStravaSuccess = "connect-with-strava-success",
  ConnectWithStravaError = "connect-with-strava-error",
  Snipe = "snipe",
  Admin = "admin",
  ActivitySearchResults = "snipe/activity-search-results",
  ActivityDetails = "snipe/activity-details",
  SnipedSegments = "snipe/sniped-segments",
}
