export enum AppRoutes {
  Home = `/app`,
  Dashboard = `/app/dashboard`,
  Register = "/app/register",
  ForgotPassword = "app/forgot-password",
  Login = "/app/login",
  Logout = "/app/logout",
  ConnectWithStravaSuccess = "/app/connect-with-strava-success",
  ConnectWithStravaError = "/app/connect-with-strava-error",
  Snipe = `/app/snipe`,
  Admin = `/app/admin`,
  ActivitySearchResults = `/app/snipe/activity-search-results`,
  ActivityDetails = `/app/snipe/activity-details`,
  SnipedSegments = `/app/snipe/sniped-segments`,
}
