/* eslint-disable no-unused-vars */
export enum AppRoutes {
  Home = '',
  Dashboard = 'dashboard',
  SignIn = 'sign-in',
  SignUp = 'sign-up',
  Logout = 'logout',
  InactiveLogout = 'inactive-logout',
  ConnectWithStrava = 'connect-strava',
  ConnectWithStravaSuccess = 'connect-with-strava-success',
  ConnectWithStravaError = 'connect-with-strava-error',
  Snipe = 'snipe',
  SegmentPredictor = 'segmentPredictor',
  Profile = 'profile',
  Admin = 'admin',
  About = 'about',
  ActivitySearchResults = 'snipe/activity-search-results',
  ActivityDetails = 'snipe/activity-details',
  SnipedSegments = 'snipe/sniped-segments',
  Garage = 'garage',
  BikeDetails = 'garage/bike-details/:bikeId',
  UserManagement = 'admin/user-management',
  ViewAssignRoles = 'admin/user-management/view-assign-roles',
  StravaWebhookManageMent = 'admin/strava-webhook-management',
  Unauthorized = 'unauthorized',
}
