// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegmentSniper.Data;

#nullable disable

namespace SegmentSniper.Data.Migrations
{
    [DbContext(typeof(SegmentSniperDbContext))]
    [Migration("20251216011335_aBunchOfStuffForSoftDeletes")]
    partial class aBunchOfStuffForSoftDeletes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SegmentSniper.Data.Entities.Garage.Bike", b =>
                {
                    b.Property<string>("BikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImportedFromStrava")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<double>("MetersLogged")
                        .HasColumnType("float");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BikeId");

                    b.HasIndex("AuthUserId", "DeletedDate");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.Garage.BikeActivity", b =>
                {
                    b.Property<Guid>("BikeActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BikeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("DistanceInMeters")
                        .HasColumnType("float");

                    b.Property<string>("StravaActivityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BikeActivityId");

                    b.HasIndex("BikeId");

                    b.HasIndex("StravaActivityId")
                        .IsUnique();

                    b.HasIndex("AuthUserId", "DeletedDate");

                    b.ToTable("BikeActivities");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.Garage.Equipment", b =>
                {
                    b.Property<string>("EquipmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BikeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InstallDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxRemindersToSend")
                        .HasColumnType("int");

                    b.Property<decimal>("MilesAtInstall")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("MilesUntilReplaceReminder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReminderDurationInMonths")
                        .HasColumnType("int");

                    b.Property<int>("RemindersSent")
                        .HasColumnType("int");

                    b.Property<int>("ReplaceAtMiles")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RetiredDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalMilage")
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EquipmentId");

                    b.HasIndex("BikeId");

                    b.HasIndex("AuthUserId", "DeletedDate");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.MachineLearning.SegmentPredictionRegressionMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("LearningRate")
                        .HasColumnType("float");

                    b.Property<double?>("LossFunction")
                        .HasColumnType("float");

                    b.Property<double?>("MeanAbsoluteError")
                        .HasColumnType("float");

                    b.Property<double?>("MeanSquaredError")
                        .HasColumnType("float");

                    b.Property<int>("MinimumExampleCountPerLeaf")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLeaves")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTrees")
                        .HasColumnType("int");

                    b.Property<double?>("RSquared")
                        .HasColumnType("float");

                    b.Property<string>("RegressionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RootMeanSquaredError")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("SegmentPredictionRegressionMetrics");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.Segments.ML_SegmentEffort", b =>
                {
                    b.Property<int>("SegmentEffortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SegmentEffortId"));

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AthleteCount")
                        .HasColumnType("int");

                    b.Property<string>("AuthUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("AverageGrade")
                        .HasColumnType("float");

                    b.Property<double?>("AverageHeartRate")
                        .HasColumnType("float");

                    b.Property<double?>("AverageSpeed")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<int?>("EffortCount")
                        .HasColumnType("int");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("int");

                    b.Property<double?>("ElevationGain")
                        .HasColumnType("float");

                    b.Property<int?>("KomTime")
                        .HasColumnType("int");

                    b.Property<double?>("MaximumGrade")
                        .HasColumnType("float");

                    b.Property<double?>("MaximumSpeed")
                        .HasColumnType("float");

                    b.Property<int?>("PrRank")
                        .HasColumnType("int");

                    b.Property<int?>("QomTime")
                        .HasColumnType("int");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SegmentPrTime")
                        .HasColumnType("int");

                    b.Property<int?>("StarCount")
                        .HasColumnType("int");

                    b.Property<string>("StravaSegmentEffortId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StravaSegmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SegmentEffortId");

                    b.HasIndex("AuthUserId");

                    b.ToTable("ML_SegmentEfforts");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.Segments.ML_SegmentPredictionModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SegmentPredictionModelData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.ToTable("ML_SegmentPredictionModels");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.StravaWebhookSubscription.StravaWebhookSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StravaWebhookSubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StravaWebhookSubscription");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.User.AppUser", b =>
                {
                    b.Property<string>("AuthUserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StravaAthleteId")
                        .HasColumnType("bigint");

                    b.Property<string>("StravaRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StravaTokenExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("StravaTokenExpiresIn")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SegmentSniper.Data.SegmentSniperDbContext+SegmentSniperLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("LogEvent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("SegmentSniperLog", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.Garage.Bike", b =>
                {
                    b.HasOne("SegmentSniper.Data.Entities.User.AppUser", "AppUser")
                        .WithMany("Bikes")
                        .HasForeignKey("AuthUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.Garage.BikeActivity", b =>
                {
                    b.HasOne("SegmentSniper.Data.Entities.User.AppUser", "AppUser")
                        .WithMany("BikeActivities")
                        .HasForeignKey("AuthUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SegmentSniper.Data.Entities.Garage.Bike", "Bike")
                        .WithMany("BikeActivities")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Bike");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.Garage.Equipment", b =>
                {
                    b.HasOne("SegmentSniper.Data.Entities.User.AppUser", "AppUser")
                        .WithMany("Equipment")
                        .HasForeignKey("AuthUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SegmentSniper.Data.Entities.Garage.Bike", "Bike")
                        .WithMany("Equipment")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Bike");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.MachineLearning.SegmentPredictionRegressionMetrics", b =>
                {
                    b.HasOne("SegmentSniper.Data.Entities.User.AppUser", "AppUser")
                        .WithOne("RegressionMetrics")
                        .HasForeignKey("SegmentSniper.Data.Entities.MachineLearning.SegmentPredictionRegressionMetrics", "AuthUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.Segments.ML_SegmentEffort", b =>
                {
                    b.HasOne("SegmentSniper.Data.Entities.User.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AuthUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.Segments.ML_SegmentPredictionModel", b =>
                {
                    b.HasOne("SegmentSniper.Data.Entities.User.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AuthUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.Garage.Bike", b =>
                {
                    b.Navigation("BikeActivities");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("SegmentSniper.Data.Entities.User.AppUser", b =>
                {
                    b.Navigation("BikeActivities");

                    b.Navigation("Bikes");

                    b.Navigation("Equipment");

                    b.Navigation("RegressionMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
